### ISSUE TITLE
Possible error in char mapping

### ISSUE THREAD

**Issue by SedatDe** [Abdullah-AlAttar/anltk#4]
Hi,

TCHEH char is defined as '\u067E' [here](https://github.com/Abdullah-AlAttar/anltk/blob/master/anltk/include/anltk/char_maps.h#L54) but it might need to be '\u0686' as in comment.

**Comment by Abdullah-AlAttar** [comment]
You are right, copy paste error, thanks for pointing it out. fixed now.
